/**
 * GENERE par tools/gen-native-assets.mjs — ne pas editer a la main.
 *
 * Relie les chemins d'assets du jeu (`/assets/...`, tels qu'ecrits dans
 * AssetLoader et les configs) aux modules que Metro empaquette. Metro exige
 * des `require()` litteraux : d'ou la generation.
 *
 * 255 entrees.
 */

export const ASSETS: Record<string, number> = {
  "/assets/buildings/archery.png": require("../assets/game/buildings/archery.png"),
  "/assets/buildings/barracks.png": require("../assets/game/buildings/barracks.png"),
  "/assets/buildings/castle.png": require("../assets/game/buildings/castle.png"),
  "/assets/buildings/house-1.png": require("../assets/game/buildings/house-1.png"),
  "/assets/buildings/house-2.png": require("../assets/game/buildings/house-2.png"),
  "/assets/buildings/house-3.png": require("../assets/game/buildings/house-3.png"),
  "/assets/buildings/monastery.png": require("../assets/game/buildings/monastery.png"),
  "/assets/buildings/tower.png": require("../assets/game/buildings/tower.png"),
  "/assets/bunnies/Bunny Sprite Sheet - Brown.png": require("../assets/game/bunnies/Bunny Sprite Sheet - Brown.png"),
  "/assets/bunnies/Bunny Sprite Sheet - Gray.png": require("../assets/game/bunnies/Bunny Sprite Sheet - Gray.png"),
  "/assets/bunnies/Bunny Sprite Sheet - Orange.png": require("../assets/game/bunnies/Bunny Sprite Sheet - Orange.png"),
  "/assets/bunnies/Bunny Sprite Sheet - White.png": require("../assets/game/bunnies/Bunny Sprite Sheet - White.png"),
  "/assets/bunnies/Bunny Sprite Sheet - Yellowish.png": require("../assets/game/bunnies/Bunny Sprite Sheet - Yellowish.png"),
  "/assets/bunnies/elecrictiy.json": require("../assets/game/bunnies/elecrictiy.json"),
  "/assets/bunnies/elecrictiy.png": require("../assets/game/bunnies/elecrictiy.png"),
  "/assets/bunnies/electrocuted.json": require("../assets/game/bunnies/electrocuted.json"),
  "/assets/bunnies/electrocuted.png": require("../assets/game/bunnies/electrocuted.png"),
  "/assets/bunnies/grass.json": require("../assets/game/bunnies/grass.json"),
  "/assets/bunnies/grass.png": require("../assets/game/bunnies/grass.png"),
  "/assets/bunnies/RR-Ghost-Down.png": require("../assets/game/bunnies/RR-Ghost-Down.png"),
  "/assets/bunnies/RR-Ghost-Up.png": require("../assets/game/bunnies/RR-Ghost-Up.png"),
  "/assets/bunnies/RR-Skull.png": require("../assets/game/bunnies/RR-Skull.png"),
  "/assets/carottes/carrote.json": require("../assets/game/carottes/carrote.json"),
  "/assets/carottes/carrote.png": require("../assets/game/carottes/carrote.png"),
  "/assets/clouds/Clouds_01.png": require("../assets/game/clouds/Clouds_01.png"),
  "/assets/clouds/Clouds_02.png": require("../assets/game/clouds/Clouds_02.png"),
  "/assets/clouds/Clouds_03.png": require("../assets/game/clouds/Clouds_03.png"),
  "/assets/clouds/Clouds_04.png": require("../assets/game/clouds/Clouds_04.png"),
  "/assets/clouds/Clouds_05.png": require("../assets/game/clouds/Clouds_05.png"),
  "/assets/clouds/Clouds_06.png": require("../assets/game/clouds/Clouds_06.png"),
  "/assets/clouds/Clouds_07.png": require("../assets/game/clouds/Clouds_07.png"),
  "/assets/clouds/Clouds_08.png": require("../assets/game/clouds/Clouds_08.png"),
  "/assets/deco/bushes/bushe1.png": require("../assets/game/deco/bushes/bushe1.png"),
  "/assets/deco/bushes/bushe2.png": require("../assets/game/deco/bushes/bushe2.png"),
  "/assets/deco/bushes/bushe3.png": require("../assets/game/deco/bushes/bushe3.png"),
  "/assets/deco/bushes/bushe4.png": require("../assets/game/deco/bushes/bushe4.png"),
  "/assets/deco/duck.png": require("../assets/game/deco/duck.png"),
  "/assets/deco/prop-01.png": require("../assets/game/deco/prop-01.png"),
  "/assets/deco/prop-02.png": require("../assets/game/deco/prop-02.png"),
  "/assets/deco/prop-03.png": require("../assets/game/deco/prop-03.png"),
  "/assets/deco/prop-04.png": require("../assets/game/deco/prop-04.png"),
  "/assets/deco/prop-05.png": require("../assets/game/deco/prop-05.png"),
  "/assets/deco/prop-06.png": require("../assets/game/deco/prop-06.png"),
  "/assets/deco/prop-07.png": require("../assets/game/deco/prop-07.png"),
  "/assets/deco/prop-08.png": require("../assets/game/deco/prop-08.png"),
  "/assets/deco/prop-09.png": require("../assets/game/deco/prop-09.png"),
  "/assets/deco/prop-10.png": require("../assets/game/deco/prop-10.png"),
  "/assets/deco/prop-11.png": require("../assets/game/deco/prop-11.png"),
  "/assets/deco/prop-12.png": require("../assets/game/deco/prop-12.png"),
  "/assets/deco/prop-13.png": require("../assets/game/deco/prop-13.png"),
  "/assets/deco/prop-14.png": require("../assets/game/deco/prop-14.png"),
  "/assets/deco/prop-15.png": require("../assets/game/deco/prop-15.png"),
  "/assets/deco/prop-16.png": require("../assets/game/deco/prop-16.png"),
  "/assets/deco/prop-17.png": require("../assets/game/deco/prop-17.png"),
  "/assets/deco/prop-18.png": require("../assets/game/deco/prop-18.png"),
  "/assets/deco/trees.json": require("../assets/game/deco/trees.json"),
  "/assets/deco/trees.png": require("../assets/game/deco/trees.png"),
  "/assets/fx/bird.json": require("../assets/game/fx/bird.json"),
  "/assets/fx/bird.png": require("../assets/game/fx/bird.png"),
  "/assets/fx/bomb-mask.png": require("../assets/game/fx/bomb-mask.png"),
  "/assets/fx/bunny-mask.png": require("../assets/game/fx/bunny-mask.png"),
  "/assets/fx/carrot-mask.png": require("../assets/game/fx/carrot-mask.png"),
  "/assets/fx/caustic-fade.png": require("../assets/game/fx/caustic-fade.png"),
  "/assets/fx/caustic-highlight.png": require("../assets/game/fx/caustic-highlight.png"),
  "/assets/fx/caustic-move.png": require("../assets/game/fx/caustic-move.png"),
  "/assets/fx/caustic.png": require("../assets/game/fx/caustic.png"),
  "/assets/fx/explosion.png": require("../assets/game/fx/explosion.png"),
  "/assets/fx/lightning-1.png": require("../assets/game/fx/lightning-1.png"),
  "/assets/fx/lightning-2.png": require("../assets/game/fx/lightning-2.png"),
  "/assets/fx/lightning-bolt.png": require("../assets/game/fx/lightning-bolt.png"),
  "/assets/fx/loot-box.json": require("../assets/game/fx/loot-box.json"),
  "/assets/fx/loot-box.png": require("../assets/game/fx/loot-box.png"),
  "/assets/fx/perlin-noise.png": require("../assets/game/fx/perlin-noise.png"),
  "/assets/fx/water-splash.png": require("../assets/game/fx/water-splash.png"),
  "/assets/gauge/bar-fill-carrot-cap.png": require("../assets/game/gauge/bar-fill-carrot-cap.png"),
  "/assets/gauge/bar-fill-carrot-mid.png": require("../assets/game/gauge/bar-fill-carrot-mid.png"),
  "/assets/gauge/bar-fill-danger-cap.png": require("../assets/game/gauge/bar-fill-danger-cap.png"),
  "/assets/gauge/bar-fill-danger-mid.png": require("../assets/game/gauge/bar-fill-danger-mid.png"),
  "/assets/gauge/bar-fill-warn-cap.png": require("../assets/game/gauge/bar-fill-warn-cap.png"),
  "/assets/gauge/bar-fill-warn-mid.png": require("../assets/game/gauge/bar-fill-warn-mid.png"),
  "/assets/gauge/bar-shell-base.png": require("../assets/game/gauge/bar-shell-base.png"),
  "/assets/gauge/bar-shell-cap.png": require("../assets/game/gauge/bar-shell-cap.png"),
  "/assets/gauge/bar-shell-mid.png": require("../assets/game/gauge/bar-shell-mid.png"),
  "/assets/gauge/dial-empty-ring.png": require("../assets/game/gauge/dial-empty-ring.png"),
  "/assets/gauge/dial-empty.png": require("../assets/game/gauge/dial-empty.png"),
  "/assets/gauge/dial-full-ring.png": require("../assets/game/gauge/dial-full-ring.png"),
  "/assets/gauge/dial-full.png": require("../assets/game/gauge/dial-full.png"),
  "/assets/island/burrow_generated.png": require("../assets/game/island/burrow_generated.png"),
  "/assets/island/burrow_lvl2.png": require("../assets/game/island/burrow_lvl2.png"),
  "/assets/island/burrow_lvl3.png": require("../assets/game/island/burrow_lvl3.png"),
  "/assets/island/burrow_lvl4.png": require("../assets/game/island/burrow_lvl4.png"),
  "/assets/island/burrow.png": require("../assets/game/island/burrow.png"),
  "/assets/island/land1.png": require("../assets/game/island/land1.png"),
  "/assets/island/land2.png": require("../assets/game/island/land2.png"),
  "/assets/island/land3.png": require("../assets/game/island/land3.png"),
  "/assets/misc/carrote_silouhette.png": require("../assets/game/misc/carrote_silouhette.png"),
  "/assets/misc/loot-box.json": require("../assets/game/misc/loot-box.json"),
  "/assets/misc/loot-box.png": require("../assets/game/misc/loot-box.png"),
  "/assets/misc/RR-Bomb-Small.png": require("../assets/game/misc/RR-Bomb-Small.png"),
  "/assets/nft/genesis-common.png": require("../assets/game/nft/genesis-common.png"),
  "/assets/nft/genesis-epic.png": require("../assets/game/nft/genesis-epic.png"),
  "/assets/nft/genesis-legendary.png": require("../assets/game/nft/genesis-legendary.png"),
  "/assets/nft/genesis-rare.png": require("../assets/game/nft/genesis-rare.png"),
  "/assets/nft/genesis-sealed.png": require("../assets/game/nft/genesis-sealed.png"),
  "/assets/sound/speaker-off.png": require("../assets/game/sound/speaker-off.png"),
  "/assets/sound/speaker-on.png": require("../assets/game/sound/speaker-on.png"),
  "/assets/terrain-iso/foam.png": require("../assets/game/terrain-iso/foam.png"),
  "/assets/terrain-iso/pack-foam.png": require("../assets/game/terrain-iso/pack-foam.png"),
  "/assets/terrain-iso/pack-shadow.png": require("../assets/game/terrain-iso/pack-shadow.png"),
  "/assets/terrain-iso/palette-1.png": require("../assets/game/terrain-iso/palette-1.png"),
  "/assets/terrain-iso/palette-2.png": require("../assets/game/terrain-iso/palette-2.png"),
  "/assets/terrain-iso/palette-3.png": require("../assets/game/terrain-iso/palette-3.png"),
  "/assets/terrain-iso/palette-4.png": require("../assets/game/terrain-iso/palette-4.png"),
  "/assets/terrain-iso/palette-5.png": require("../assets/game/terrain-iso/palette-5.png"),
  "/assets/terrain-iso/tilemap-elevation.png": require("../assets/game/terrain-iso/tilemap-elevation.png"),
  "/assets/terrain-iso/tilemap-flat.png": require("../assets/game/terrain-iso/tilemap-flat.png"),
  "/assets/terrain/archery.png": require("../assets/game/terrain/archery.png"),
  "/assets/terrain/foam.png": require("../assets/game/terrain/foam.png"),
  "/assets/terrain/palette-1.png": require("../assets/game/terrain/palette-1.png"),
  "/assets/terrain/palette-2.png": require("../assets/game/terrain/palette-2.png"),
  "/assets/terrain/palette-3.png": require("../assets/game/terrain/palette-3.png"),
  "/assets/terrain/palette-4.png": require("../assets/game/terrain/palette-4.png"),
  "/assets/terrain/palette-5.png": require("../assets/game/terrain/palette-5.png"),
  "/assets/terrain/sea-rock-01.png": require("../assets/game/terrain/sea-rock-01.png"),
  "/assets/terrain/sea-rock-02.png": require("../assets/game/terrain/sea-rock-02.png"),
  "/assets/terrain/sea-rock-03.png": require("../assets/game/terrain/sea-rock-03.png"),
  "/assets/terrain/sea-rock-04.png": require("../assets/game/terrain/sea-rock-04.png"),
  "/assets/terrain/tilemap-elevation.png": require("../assets/game/terrain/tilemap-elevation.png"),
  "/assets/terrain/tilemap-flat.png": require("../assets/game/terrain/tilemap-flat.png"),
  "/assets/terrain/water.png": require("../assets/game/terrain/water.png"),
  "/assets/ui/badge.png": require("../assets/game/ui/badge.png"),
  "/assets/ui/banner.png": require("../assets/game/ui/banner.png"),
  "/assets/ui/close-default.png": require("../assets/game/ui/close-default.png"),
  "/assets/ui/close-hover.png": require("../assets/game/ui/close-hover.png"),
  "/assets/ui/close-pressed.png": require("../assets/game/ui/close-pressed.png"),
  "/assets/ui/crown.png": require("../assets/game/ui/crown.png"),
  "/assets/ui/cursors/arrow.png": require("../assets/game/ui/cursors/arrow.png"),
  "/assets/ui/cursors/denied.png": require("../assets/game/ui/cursors/denied.png"),
  "/assets/ui/cursors/hand.png": require("../assets/game/ui/cursors/hand.png"),
  "/assets/ui/heart-empty.png": require("../assets/game/ui/heart-empty.png"),
  "/assets/ui/heart.png": require("../assets/game/ui/heart.png"),
  "/assets/ui/icons/bolt.png": require("../assets/game/ui/icons/bolt.png"),
  "/assets/ui/icons/bomb-lit.png": require("../assets/game/ui/icons/bomb-lit.png"),
  "/assets/ui/icons/bomb.png": require("../assets/game/ui/icons/bomb.png"),
  "/assets/ui/icons/carrot.png": require("../assets/game/ui/icons/carrot.png"),
  "/assets/ui/icons/fertiliser.png": require("../assets/game/ui/icons/fertiliser.png"),
  "/assets/ui/icons/garden.png": require("../assets/game/ui/icons/garden.png"),
  "/assets/ui/icons/shield.png": require("../assets/game/ui/icons/shield.png"),
  "/assets/ui/icons/shop.png": require("../assets/game/ui/icons/shop.png"),
  "/assets/ui/icons/swords.png": require("../assets/game/ui/icons/swords.png"),
  "/assets/ui/icons/water.png": require("../assets/game/ui/icons/water.png"),
  "/assets/ui/leaf-frame.png": require("../assets/game/ui/leaf-frame.png"),
  "/assets/ui/plank.png": require("../assets/game/ui/plank.png"),
  "/assets/ui/ring-1.png": require("../assets/game/ui/ring-1.png"),
  "/assets/ui/ring-2.png": require("../assets/game/ui/ring-2.png"),
  "/assets/ui/ring-3.png": require("../assets/game/ui/ring-3.png"),
  "/assets/ui/rr-logo-1x.png": require("../assets/game/ui/rr-logo-1x.png"),
  "/assets/ui/rr-logo-banner.png": require("../assets/game/ui/rr-logo-banner.png"),
  "/assets/ui/scroll-plank.png": require("../assets/game/ui/scroll-plank.png"),
  "/assets/ui/scroll.png": require("../assets/game/ui/scroll.png"),
  "/assets/ui/skull-plank.png": require("../assets/game/ui/skull-plank.png"),
  "/assets/units/archer-blue.png": require("../assets/game/units/archer-blue.png"),
  "/assets/units/pawn-blue.png": require("../assets/game/units/pawn-blue.png"),
  "/assets/units/pawn-red.png": require("../assets/game/units/pawn-red.png"),
  "/assets/units/sheep-bounce.png": require("../assets/game/units/sheep-bounce.png"),
  "/assets/units/sheep-idle.png": require("../assets/game/units/sheep-idle.png"),
  "/assets/units/torch-red.png": require("../assets/game/units/torch-red.png"),
  "/assets/units/warrior-blue.png": require("../assets/game/units/warrior-blue.png"),
  "/assets/units/warrior-red.png": require("../assets/game/units/warrior-red.png"),
  "/assets/world/decor/bush-round.png": require("../assets/game/world/decor/bush-round.png"),
  "/assets/world/decor/bush-small.png": require("../assets/game/world/decor/bush-small.png"),
  "/assets/world/decor/flower-leafy.png": require("../assets/game/world/decor/flower-leafy.png"),
  "/assets/world/decor/flower-tall.png": require("../assets/game/world/decor/flower-tall.png"),
  "/assets/world/decor/flowers-patch.png": require("../assets/game/world/decor/flowers-patch.png"),
  "/assets/world/decor/flowers-small.png": require("../assets/game/world/decor/flowers-small.png"),
  "/assets/world/decor/hill-big.png": require("../assets/game/world/decor/hill-big.png"),
  "/assets/world/decor/hill-wide.png": require("../assets/game/world/decor/hill-wide.png"),
  "/assets/world/decor/manifest.json": require("../assets/game/world/decor/manifest.json"),
  "/assets/world/decor/meadow-tuft.png": require("../assets/game/world/decor/meadow-tuft.png"),
  "/assets/world/decor/tuft-left.png": require("../assets/game/world/decor/tuft-left.png"),
  "/assets/world/decor/tuft-right.png": require("../assets/game/world/decor/tuft-right.png"),
  "/assets/world/decor/tuft-small.png": require("../assets/game/world/decor/tuft-small.png"),
  "/assets/world/green_nature_iso_decor_elements.png": require("../assets/game/world/green_nature_iso_decor_elements.png"),
  "/assets/world/iso-cloud-01.png": require("../assets/game/world/iso-cloud-01.png"),
  "/assets/world/iso-cloud-02.png": require("../assets/game/world/iso-cloud-02.png"),
  "/assets/world/iso-smooth-sheet-128.png": require("../assets/game/world/iso-smooth-sheet-128.png"),
  "/assets/world/isometric-sandbox-sheet-32x32.png": require("../assets/game/world/isometric-sandbox-sheet-32x32.png"),
  "/assets/world/nature-isoworld.png": require("../assets/game/world/nature-isoworld.png"),
  "/assets/world/rabbit_green-nature.png": require("../assets/game/world/rabbit_green-nature.png"),
  "/kit/fonts/d8-font-8x7-outline.png": require("../assets/kit/fonts/d8-font-8x7-outline.png"),
  "/kit/fonts/d8-font-basic-8x8.png": require("../assets/kit/fonts/d8-font-basic-8x8.png"),
  "/kit/game/blood-spritesheet.png": require("../assets/kit/game/blood-spritesheet.png"),
  "/kit/game/bonk.png": require("../assets/kit/game/bonk.png"),
  "/kit/game/carrot.png": require("../assets/kit/game/carrot.png"),
  "/kit/game/d8-loot-box.png": require("../assets/kit/game/d8-loot-box.png"),
  "/kit/game/darthvader.png": require("../assets/kit/game/darthvader.png"),
  "/kit/game/fight-effect.png": require("../assets/kit/game/fight-effect.png"),
  "/kit/game/fish.png": require("../assets/kit/game/fish.png"),
  "/kit/game/hp-bar-empty.png": require("../assets/kit/game/hp-bar-empty.png"),
  "/kit/game/hp-bar-orange.png": require("../assets/kit/game/hp-bar-orange.png"),
  "/kit/game/hp-bar-red.png": require("../assets/kit/game/hp-bar-red.png"),
  "/kit/game/hp-bar.png": require("../assets/kit/game/hp-bar.png"),
  "/kit/game/huggywuggy.png": require("../assets/kit/game/huggywuggy.png"),
  "/kit/game/mermaid.png": require("../assets/kit/game/mermaid.png"),
  "/kit/game/monke.png": require("../assets/kit/game/monke.png"),
  "/kit/game/orc.png": require("../assets/kit/game/orc.png"),
  "/kit/game/pepe.png": require("../assets/kit/game/pepe.png"),
  "/kit/game/throne.png": require("../assets/kit/game/throne.png"),
  "/kit/game/yasuo.png": require("../assets/kit/game/yasuo.png"),
  "/kit/sprites/bars/d8-bar-coal.png": require("../assets/kit/sprites/bars/d8-bar-coal.png"),
  "/kit/sprites/bars/d8-bar-dirty-gold.png": require("../assets/kit/sprites/bars/d8-bar-dirty-gold.png"),
  "/kit/sprites/bars/d8-bar-gold.png": require("../assets/kit/sprites/bars/d8-bar-gold.png"),
  "/kit/sprites/bars/d8-bar-hell.png": require("../assets/kit/sprites/bars/d8-bar-hell.png"),
  "/kit/sprites/bars/d8-bar-silver.png": require("../assets/kit/sprites/bars/d8-bar-silver.png"),
  "/kit/sprites/bars/d8-bar-titanium.png": require("../assets/kit/sprites/bars/d8-bar-titanium.png"),
  "/kit/sprites/d8-gold-cup.png": require("../assets/kit/sprites/d8-gold-cup.png"),
  "/kit/sprites/d8-golden-coin-0001.png": require("../assets/kit/sprites/d8-golden-coin-0001.png"),
  "/kit/sprites/d8-golden-coin-0002.png": require("../assets/kit/sprites/d8-golden-coin-0002.png"),
  "/kit/sprites/d8-golden-coin-0003.png": require("../assets/kit/sprites/d8-golden-coin-0003.png"),
  "/kit/sprites/d8-golden-coin-0004.png": require("../assets/kit/sprites/d8-golden-coin-0004.png"),
  "/kit/sprites/d8-golden-coin-0005.png": require("../assets/kit/sprites/d8-golden-coin-0005.png"),
  "/kit/sprites/d8-golden-coin-0006.png": require("../assets/kit/sprites/d8-golden-coin-0006.png"),
  "/kit/sprites/d8-vault-big.png": require("../assets/kit/sprites/d8-vault-big.png"),
  "/kit/sprites/d8-vault-small.png": require("../assets/kit/sprites/d8-vault-small.png"),
  "/kit/sprites/d8-vault-title.png": require("../assets/kit/sprites/d8-vault-title.png"),
  "/kit/sprites/jewels/d8-jewel-amber.png": require("../assets/kit/sprites/jewels/d8-jewel-amber.png"),
  "/kit/sprites/jewels/d8-jewel-blue.png": require("../assets/kit/sprites/jewels/d8-jewel-blue.png"),
  "/kit/sprites/jewels/d8-jewel-green-deep.png": require("../assets/kit/sprites/jewels/d8-jewel-green-deep.png"),
  "/kit/sprites/jewels/d8-jewel-green.png": require("../assets/kit/sprites/jewels/d8-jewel-green.png"),
  "/kit/sprites/jewels/d8-jewel-ice.png": require("../assets/kit/sprites/jewels/d8-jewel-ice.png"),
  "/kit/sprites/jewels/d8-jewel-jade.png": require("../assets/kit/sprites/jewels/d8-jewel-jade.png"),
  "/kit/sprites/jewels/d8-jewel-orange.png": require("../assets/kit/sprites/jewels/d8-jewel-orange.png"),
  "/kit/sprites/jewels/d8-jewel-purple.png": require("../assets/kit/sprites/jewels/d8-jewel-purple.png"),
  "/kit/sprites/jewels/d8-jewel-red.png": require("../assets/kit/sprites/jewels/d8-jewel-red.png"),
  "/kit/sprites/jewels/d8-jewel-turquoise.png": require("../assets/kit/sprites/jewels/d8-jewel-turquoise.png"),
  "/kit/sprites/jewels/d8-jewel-violet.png": require("../assets/kit/sprites/jewels/d8-jewel-violet.png"),
  "/kit/ui/d8-arrow-down.png": require("../assets/kit/ui/d8-arrow-down.png"),
  "/kit/ui/d8-arrow-left.png": require("../assets/kit/ui/d8-arrow-left.png"),
  "/kit/ui/d8-arrow-right.png": require("../assets/kit/ui/d8-arrow-right.png"),
  "/kit/ui/d8-arrow-up.png": require("../assets/kit/ui/d8-arrow-up.png"),
  "/kit/ui/d8-button-fill-pressed.png": require("../assets/kit/ui/d8-button-fill-pressed.png"),
  "/kit/ui/d8-button-fill.png": require("../assets/kit/ui/d8-button-fill.png"),
  "/kit/ui/d8-button-frame-pressed.png": require("../assets/kit/ui/d8-button-frame-pressed.png"),
  "/kit/ui/d8-button-frame.png": require("../assets/kit/ui/d8-button-frame.png"),
  "/kit/ui/d8-button-highlight-pressed.png": require("../assets/kit/ui/d8-button-highlight-pressed.png"),
  "/kit/ui/d8-button-highlight.png": require("../assets/kit/ui/d8-button-highlight.png"),
  "/kit/ui/d8-button-outline-pressed.png": require("../assets/kit/ui/d8-button-outline-pressed.png"),
  "/kit/ui/d8-button-outline.png": require("../assets/kit/ui/d8-button-outline.png"),
  "/kit/ui/d8-chat-bubble.png": require("../assets/kit/ui/d8-chat-bubble.png"),
  "/kit/ui/d8-dithered-gradient-32x.png": require("../assets/kit/ui/d8-dithered-gradient-32x.png"),
  "/kit/ui/d8-dithered-gradient-64x.png": require("../assets/kit/ui/d8-dithered-gradient-64x.png"),
  "/kit/ui/d8-glove-pointer.png": require("../assets/kit/ui/d8-glove-pointer.png"),
  "/kit/ui/d8-panel-bg.png": require("../assets/kit/ui/d8-panel-bg.png"),
  "/kit/ui/d8-panel-cashout-bg.png": require("../assets/kit/ui/d8-panel-cashout-bg.png"),
  "/kit/ui/d8-panel-shade.png": require("../assets/kit/ui/d8-panel-shade.png"),
};

/**
 * Le module Metro d'un chemin d'asset, ou null s'il n'est pas empaquete.
 *
 * Tolerant sur la forme du chemin : le Resolver de Pixi retire le slash
 * initial ("/assets/x.png" -> "assets/x.png") et peut prefixer une base URL.
 * On normalise donc avant de chercher, et on retombe sur le .png jumeau
 * quand le jeu reference un .webp (que stb_image ne sait pas decoder).
 */
export function moduleDe(url: string): number | null {
  if (typeof url !== 'string' || url.length === 0) return null;

  // Ne garder que la partie a partir de "/assets/", sans query ni ancre.
  let chemin = url.split('?')[0].split('#')[0];
  const i = chemin.indexOf('assets/');
  if (i === -1) return null;
  chemin = '/' + chemin.slice(i);

  const png = chemin.replace(/\.webp$/i, '.png');
  return ASSETS[chemin] ?? ASSETS[png] ?? null;
}
